# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "taxonifi"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mjy"]
  s.date = "2013-03-27"
  s.description = "Taxonifi contains simple models and utilties of use in for parsing lists of taxonomic name (life) related metadata"
  s.email = "diapriid@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/assessor/assessor.rb",
    "lib/assessor/base.rb",
    "lib/assessor/row_assessor.rb",
    "lib/export/export.rb",
    "lib/export/format/base.rb",
    "lib/export/format/obo_nomenclature.rb",
    "lib/export/format/prolog.rb",
    "lib/export/format/species_file.rb",
    "lib/lumper/clump.rb",
    "lib/lumper/lumper.rb",
    "lib/lumper/lumps/parent_child_name_collection.rb",
    "lib/models/author_year.rb",
    "lib/models/base.rb",
    "lib/models/collection.rb",
    "lib/models/generic_object.rb",
    "lib/models/geog.rb",
    "lib/models/geog_collection.rb",
    "lib/models/name.rb",
    "lib/models/name_collection.rb",
    "lib/models/person.rb",
    "lib/models/ref.rb",
    "lib/models/ref_collection.rb",
    "lib/models/shared_class_methods.rb",
    "lib/models/species_name.rb",
    "lib/splitter/builder.rb",
    "lib/splitter/lexer.rb",
    "lib/splitter/parser.rb",
    "lib/splitter/splitter.rb",
    "lib/splitter/tokens.rb",
    "lib/taxonifi.rb",
    "lib/utils/array.rb",
    "lib/utils/hash.rb",
    "taxonifi.gemspec",
    "test/file_fixtures/Fossil.csv",
    "test/file_fixtures/Lygaeoidea.csv",
    "test/file_fixtures/names.csv",
    "test/helper.rb",
    "test/test_export_prolog.rb",
    "test/test_exporter.rb",
    "test/test_lumper_clump.rb",
    "test/test_lumper_geogs.rb",
    "test/test_lumper_hierarchical_collection.rb",
    "test/test_lumper_names.rb",
    "test/test_lumper_parent_child_name_collection.rb",
    "test/test_lumper_refs.rb",
    "test/test_obo_nomenclature.rb",
    "test/test_parser.rb",
    "test/test_splitter.rb",
    "test/test_splitter_tokens.rb",
    "test/test_taxonifi.rb",
    "test/test_taxonifi_accessor.rb",
    "test/test_taxonifi_base.rb",
    "test/test_taxonifi_geog.rb",
    "test/test_taxonifi_name.rb",
    "test/test_taxonifi_name_collection.rb",
    "test/test_taxonifi_ref.rb",
    "test/test_taxonifi_ref_collection.rb",
    "test/test_taxonifi_species_name.rb"
  ]
  s.homepage = "http://github.com/SpeciesFile/taxonifi"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "A general purpose framework for scripted handling of taxonomic names"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<activerecord>, ["= 3.2.8"])
      s.add_development_dependency(%q<debugger>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<activerecord>, ["= 3.2.8"])
      s.add_dependency(%q<debugger>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<activerecord>, ["= 3.2.8"])
    s.add_dependency(%q<debugger>, [">= 0"])
  end
end

